// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package keyval

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PutRsp struct {
	_tab flatbuffers.Table
}

func GetRootAsPutRsp(buf []byte, offset flatbuffers.UOffsetT) *PutRsp {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PutRsp{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *PutRsp) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PutRsp) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PutRsp) Added() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PutRsp) MutateAdded(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func PutRspStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PutRspAddAdded(builder *flatbuffers.Builder, added byte) {
	builder.PrependByteSlot(0, added, 0)
}
func PutRspEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
